=== davidescar/DressCode/DressCode/Progetto/data/ordini.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://informatica.math.unipd.it"
    targetNamespace="http://informatica.math.unipd.it">
    <xs:element name="ordiniEffettuati" type="order_list" />
	<xs:complexType name="order_list">
		<xs:sequence>
	        <xs:element name="ordine" type="order_info" minOccurs="0" maxOccurs="unbounded" />
	    </xs:sequence>
	</xs:complexType>
	<xs:complexType name="order_info">
	   	<xs:sequence>
			<xs:element name="email" type="xs:string" />
			<xs:element name="data" type="xs:date" />
			<xs:element name="prodottiAcquistati" type="products_list" />
		</xs:sequence>
		<xs:attribute name="codice" type="xs:string" use="required" />
		<xs:attribute name="spedizione" type="xs:string" use="required" />
	</xs:complexType>
	<xs:complexType name="products_list">
		<xs:sequence>
			<xs:element name="prodotto" type="prod_info" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="prod_info">
		<xs:sequence>
			<xs:element name="codice" type="xs:string" />
			<xs:element name="nome" type="xs:string" />
			<xs:element name="prezzo" type="xs:decimal" />
			<xs:element name="taglia" type="xs:string" />
			<xs:element name="colore" type="xs:string" />
			<xs:element name="quantitÃ " type="xs:positiveInteger" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== davidescar/DressCode/DressCode/Progetto/data/ordini.xml
<?xml version="1.0" encoding="UTF-8"?>
<so:ordiniEffettuati xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xmlns:so="http://informatica.math.unipd.it" xs:schemaLocation="http://informatica.math.unipd.it ordini.xsd">
	<ordine codice="00001" spedizione="standard">
		<email>base@gmail.com</email>
		<data>2016-01-15</data>
		<prodottiAcquistati>
			<prodotto>
				<codice>00050</codice>
				<nome>Extreme</nome>
				<prezzo>21.60</prezzo>
				<taglia>XS</taglia>
				<colore>Azzurro</colore>
				<quantita>2</quantita>
			</prodotto>
			<prodotto>
				<codice>00001</codice>
				<nome>Misfits</nome>
				<prezzo>52.00</prezzo>
				<taglia>S</taglia>
				<colore>Azzurro</colore>
				<quantita>2</quantita>
			</prodotto>
			<prodotto>
				<codice>00117</codice>
				<nome>Nitjackon</nome>
				<prezzo>18.00</prezzo>
				<taglia>XS</taglia>
				<colore>Nero</colore>
				<quantita>2</quantita>
			</prodotto>
		</prodottiAcquistati>
	</ordine>
	<ordine codice="00002" spedizione="gratuita">
		<email>prova@prova.com</email>
		<data>2016-01-17</data>
		<prodottiAcquistati>
			<prodotto>
				<codice>00050</codice>
				<nome>Extreme</nome>
				<prezzo>21.60</prezzo>
				<taglia>XS</taglia>
				<colore>Azzurro</colore>
				<quantita>1</quantita>
			</prodotto>
		</prodottiAcquistati>
	</ordine>
</so:ordiniEffettuati>
