=== davidescar/DressCode/DressCode/Progetto/data/prodotti.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://informatica.math.unipd.it"
    targetNamespace="http://informatica.math.unipd.it">
    <xs:element name="catalogo" type="catalogo_type" />
    <xs:complexType name="catalogo_type">
        <xs:sequence>
            <xs:element name="prodotto" type="product_type" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="product_type">
        <xs:all>
            <xs:element name="nome" type="xs:string" />
            <xs:element name="materiale" type="xs:string" />
            <xs:element name="tipologia" type="xs:string" />   
            <xs:element name="categoria" type="xs:string" />
            <xs:element name="prezzo" type="price_type" />
            <xs:element name="descrizione" type="xs:string" />            
            <xs:element name="taglieDisponibili" type="taglie_list_type" minOccurs="0" maxOccurs="1" />
            <xs:element name="coloriDisponibili" type="colori_list_type" minOccurs="0" maxOccurs="1" />
            <xs:element name="immaginiProdotto" type="immagini_list_type" />
        </xs:all>
        <xs:attribute name="codice" type="xs:string" use="required" />
    </xs:complexType>
    <xs:complexType name="taglie_list_type">
        <xs:sequence>
            <xs:element name="taglia" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="colori_list_type">
        <xs:sequence>
            <xs:element name="colore" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="immagini_list_type">
        <xs:sequence>
            <xs:element name="immagine" type="xs:string" minOccurs="0" maxOccurs="3" />
        </xs:sequence>
    </xs:complexType>
	<xs:complexType name="price_type">
		<xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="valuta" type="xs:string" use="required" />
                 <xs:attribute name="sconto" type="xs:nonNegativeInteger" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== davidescar/DressCode/DressCode/Progetto/data/prodotti.xml
<?xml version="1.0" encoding="UTF-8"?>
<so:catalogo xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xmlns:so="http://informatica.math.unipd.it" xs:schemaLocation="http://informatica.math.unipd.it prodotti.xsd">
	<prodotto codice="00001">
		<nome>Misfits</nome>
		<materiale>Jeans</materiale>
		<tipologia>Pantalone</tipologia>
		<categoria>Uomo</categoria>
		<prezzo valuta="euro" sconto="0">52.00</prezzo>
		<descrizione>Jeans skinny di ottima qualit&amp;agrave; adatto per ogni occasione</descrizione>
		<taglieDisponibili>
			<taglia>S</taglia>
			<taglia>M</taglia>
		</taglieDisponibili>
		<coloriDisponibili>
			<colore>Azzurro</colore>
			<colore>Blu</colore>
		</coloriDisponibili>
		<immaginiProdotto>
			<immagine>jeans001.jpg</immagine>
			<immagine>jeans002.jpg</immagine>
			<immagine>jeans003.jpg</immagine>
		</immaginiProdotto>
	</prodotto>
	<prodotto codice="00002">
		<nome>Chishaped</nome>
		<materiale>Jeans</materiale>
		<tipologia>Pantalone</tipologia>
		<categoria>Uomo</categoria>
		<prezzo valuta="euro" sconto="0">75.50</prezzo>
		<descrizione>Jeans scuro classico, leggermente sbiadito ad altezza ginocchia. Di ottima fattura</descrizione>
		<taglieDisponibili>
			<taglia>S</taglia>
			<taglia>M</taglia>
			<taglia>L</taglia>
		</taglieDisponibili>
		<coloriDisponibili>
			<colore>Nero</colore>
			<colore>Blu</colore>
		</coloriDisponibili>
		<immaginiProdotto>
			<immagine>jeans004.jpg</immagine>
			<immagine>jeans005.jpg</immagine>
			<immagine>jeans006.jpg</immagine>
		</immaginiProdotto>
	</prodotto>
	<prodotto codice="00003">
		<nome>Thavar</nome>
		<materiale>Jeans</materiale>
		<tipologia>Pantalone</tipologia>
		<categoria>Uomo</categoria>
		<prezzo valuta="euro" sconto="20">70.00</prezzo>
		<descrizione>Jeans skinny chiaro con un ottimo rapporto qualit&amp;agrave; prezzo</descrizione>
		<taglieDisponibili>
			<taglia>L</taglia>
			<taglia>XL</taglia>
		</taglieDisponibili>
		<coloriDisponibili>
			<colore>Bianco</colore>
			<colore>Blu</colore>
			<colore>Azzurro</colore>
		</coloriDisponibili>
		<immaginiProdotto>
			<immagine>jeans007.jpg</immagine>
			<immagine>jeans008.jpg</immagine>
			<immagine>jeans009.jpg</immagine>
		</immaginiProdotto>
	</prodotto>
	<prodotto codice="00004">
		<nome>Rover</nome>
		<materiale>Sintetico</materiale>
		<tipologia>Giubbotto</tipologia>
		<categoria>Uomo</categoria>
		<prezzo valuta="euro" sconto="10">102.50</prezzo>
		<descrizione>Giubbotto scuro adatto alla stagione invernale. Rapporto qualit&amp;agrave; prezzo eccellente</descrizione>
		<taglieDisponibili>
			<taglia>S</taglia>
			<taglia>M</taglia>
			<taglia>L</taglia>
		</taglieDisponibili>
		<coloriDisponibili>
			<colore>Rosso</colore>
			<colore>Blu</colore>
			<colore>Marrone</colore>
		</coloriDisponibili>
		<immaginiProdotto>
			<immagine>giubbotto001.jpg</immagine>
			<immagine>giubbotto002.jpg</immagine>
			<immagine>giubbotto003.jpg</immagine>
		</immaginiProdotto>
	</prodotto>
	<prodotto codice="00005">
		<nome>Whistler</nome>
		<materiale>Sintetico</materiale>
		<tipologia>Giubbotto</tipologia>
		<categoria>Uomo</categoria>
		<prezzo valuta="euro" sconto="0">81.00</prezzo>
		<descrizione>Giubbotto sportivo con imbottitura in vera piuma, adatto sia alla stagione autunnale che a quella invernale</descrizione>
		<taglieDisponibili>
			<taglia>S</taglia>
			<taglia>M</taglia>
			<taglia>L</taglia>
		</taglieDisponibili>
		<coloriDisponibili>
			<colore>Nero</colore>
			<colore>Blu</colore>
			<colore>Grigio</colore>
		</coloriDisponibili>
		<immaginiProdotto>
			<immagine>giubbotto004.jpg</immagine>
			<immagine>giubbotto005.jpg</immagine>
			<immagine>giubbotto006.jpg</immagine>
		</immaginiProdotto>
	</prodotto>
	<prodotto codice="00006">
		<nome>Blake</nome>
		<materiale>Sintetico</materiale>
		<tipologia>Giubbotto</tipologia>
		<categoria>Uomo</categoria>
		<prezzo valuta="euro" sconto="0">65.00</prezzo>
		<descrizione>Giubbotto autunnale con interno particolare e molto curato</descrizione>
		<taglieDisponibili>
			<taglia>S</taglia>
			<taglia>M</taglia>
			<taglia>L</taglia>
		</taglieDisponibili>
		<coloriDisponibili>
			<colore>Giallo</colore>
			<colore>Marrone</colore>
			<colore>Verde</colore>
		</coloriDisponibili>
		<immaginiProdotto>
			<immagine>giubbotto007.jpg</immagine>
			<immagine>giubbotto008.jpg</immagine>
			<immagine>giubbotto009.jpg</immagine>
		</immaginiProdotto>
	</prodotto>
	<prodotto codice="00007">
		<nome>Reince</nome>
		<materiale>Cotone</materiale>
		<tipologia>Maglione</tipologia>
		<categoria>Uomo</categoria>
		<prezzo valuta="euro" sconto="0">39.00</prezzo>
		<descrizione>Maglione scuro di cotone molto semplice ma allo stesso tempo elegante</descrizione>
		<taglieDisponibili>
			<taglia>S</taglia>
			<taglia>M</taglia>
			<taglia>L</taglia>
		</taglieDisponibili>
		<coloriDisponibili>
			<colore>Blu</colore>
			<colore>Marrone</colore>
			<colore>Grigio</colore>
		</coloriDisponibili>
		<immaginiProdotto>
			<immagine>maglione001.jpg</immagine>
			<immagine>maglione002.jpg</immagine>
			<immagine>maglione003.jpg</immagine>
		</immaginiProdotto>
	</prodotto>
	<prodotto codice="00008">
		<nome>Satre</nome>
		<materiale>Lana</materiale>
		<tipologia>Maglione</tipologia>
		<categoria>Uomo</categoria>
		<prezzo valuta="euro" sconto="0">45.00</prezzo>
		<descrizione>Maglione di lana scuro con motivo geometrico bianco sulla parte superiore (petto e spalle)</descrizione>
		<taglieDisponibili>
			<taglia>M</taglia>
			<taglia>L</taglia>
			<taglia>XL</taglia>
		</taglieDisponibili>
		<coloriDisponibili>
			<colore>Nero</colore>
			<colore>Bianco</colore>
			<colore>Rosso</colore>
			<colore>Blu</colore>
		</coloriDisponibili>
		<immaginiProdotto>
			<immagine>maglione004.jpg</immagine>
			<immagine>maglione005.jpg</immagine>
			<immagine>maglione006.jpg</immagine>
		</immaginiProdotto>
	</prodotto>
	<prodotto codice="00009">
		<nome>Brayden</nome>
		<materiale>Cotone</materiale>
		<tipologia>Maglione</tipologia>
		<categoria>Uomo</categoria>
		<prezzo valuta="euro" sconto="15">65.00</prezzo>
		<descrizione>Maglione leggero con motivo intrecciato e chiusura con alamari</descrizione>
		<taglieDisponibili>
			<taglia>S</taglia>
			<taglia>M</taglia>
			<taglia>L</taglia>
		</taglieDisponibili>
		<coloriDisponibili>
			<colore>Blu</colore>
			<colore>Grigio</colore>
			<colore>Verde</colore>
		</coloriDisponibili>
		<immaginiProdotto>
			<immagine>maglione007.jpg</immagine>
			<immagine>maglione008.jpg</immagine>
			<immagine>maglione009.jpg</immagine>
		</immaginiProdotto>
	</prodotto>
	<prodotto codice="00010">
		<nome>Wescargo</nome>
		<materiale>Cotone</materiale>
		<tipologia>Pantalone</tipologia>
		<categoria>Uomo</categoria>
		<prezzo valuta="euro" sconto="20">72.00</prezzo>
		<descrizione>Pantalone sportivo con due tasconi laterali ed elasticizzato sulle caviglie</descrizione>
		<taglieDisponibili>
			<taglia>S</taglia>
			<taglia>M</taglia>
			<taglia>L</taglia>
		</taglieDisponibili>
		<coloriDisponibili>
			<colore>Nero</colore>
			<colore>Marrone</colore>
		</coloriDisponibili>
		<immaginiProdotto>
			<immagine>pant001.jpg</immagine>
			<immagine>pant002.jpg</immagine>
			<immagine>pant003.jpg</immagine>
		</immaginiProdotto>
	</prodotto>
	<prodotto codice="00011">
		<nome>Agent</nome>
		<materiale>Seta</materiale>
		<tipologia>Pantalone</tipologia>
		<categoria>Uomo</categoria>
		<prezzo valuta="euro" sconto="25">85.00</prezzo>
		<descrizione>Pantalone scuro di seta elasticizzato sulle caviglie</descrizione>
		<taglieDisponibili>
			<taglia>S</taglia>
			<taglia>M</taglia>
			<taglia>XL</taglia>
		</taglieDisponibili>
		<coloriDisponibili>
			<colore>Nero</colore>
			<colore>Bianco</colore>
			<colore>Grigio</colore>
		</coloriDisponibili>
		<immaginiProdotto>
			<immagine>pant004.jpg</immagine>
			<immagine>pant005.jpg</immagine>
			<immagine>pant006.jpg</immagine>
		</immaginiProdotto>
	</prodotto>
	<prodotto codice="00012">
		<nome>Oscale</nome>
		<materiale>Cotone</materiale>
		<tipologia>Pantalone</tipologia>
		<categoria>Uomo</categoria>
		<prezzo valuta="euro" sconto="35">47.00</prezzo>
		<descrizione>Pantalone classico ed elegante adatto per le occasioni mondane</descrizione>
		<taglieDisponibili>
			<taglia>M</taglia>
			<taglia>L</taglia>
		</taglieDisponibili>
		<coloriDisponibili>
			<colore>Giallo</colore>
			<colore>Blu</colore>
			<colore>Marrone</colore>
			<colore>Grigio</colore>
		</coloriDisponibili>
		<immaginiProdotto>
			<immagine>pant007.jpg</immagine>
			<immagine>pant008.jpg</immagine>
			<immagine>pant009.jpg</immagine>
		</immaginiProdotto>
	</prodotto>
	<prodotto codice="00013">
		<nome>Nisbiel</nome>
		<materiale>Cotone</materiale>
		<tipologia>Completo</tipologia>
		<categoria>Uomo</categoria>
		<prezzo valuta="euro" sconto="15">125.50</prezzo>
		<descrizione>Completo elegante di cotone adatto per occasioni importanti</descrizione>
		<taglieDisponibili>
			<taglia>S</taglia>
			<taglia>M</taglia>
			<taglia>L</taglia>
		</taglieDisponibili>
		<coloriDisponibili>
			<colore>Blu</colore>
			<colore>Grigio</colore>
		</coloriDisponibili>
		<immaginiProdotto>
			<immagine>completo001.jpg</immagine>
			<immagine>completo002.jpg</immagine>
			<immagine>completo003.jpg</immagine>
		</immaginiProdotto>
	</prodotto>
	<prodotto codice="00014">
		<nome>Vebir</nome>
		<materiale>Cotone</materiale>
		<tipologia>Completo</tipologia>
		<categoria>Uomo</categoria>
		<prezzo valuta="euro" sconto="0">106.00</prezzo>
		<descrizione>Completo scuro di cotone, classico ed elegante di ottima fattura</descrizione>
		<taglieDisponibili>
			<taglia>S</taglia>
			<taglia>XL</taglia>
		</taglieDisponibili>
		<coloriDisponibili>
			<colore>Nero</colore>
			<colore>Blu</colore>
		</coloriDisponibili>
		<immaginiProdotto>
			<immagine>completo004.jpg</immagine>
			<immagine>completo005.jpg</immagine>
			<immagine>completo006.jpg</immagine>
		</immaginiProdotto>
	</prodotto>
	<prodotto codice="00015">
		<nome>Samar</nome>
